### ISSUE TITLE
issue in line #28 and #30

### ISSUE THREAD

**Issue by hero4000** [jromerooo2/BonziBuddy-Assistant#1]
![image](https://user-images.githubusercontent.com/114915887/193551794-12e9567d-65c3-4c8c-b174-81edc54561d4.png)

![image](https://user-images.githubusercontent.com/114915887/193551866-06b3af9b-8e0e-48f6-9191-6aee11b51e86.png)

how to fix this can you fix it? and thanks i need this script im a python begainner

**Comment by jromerooo2** [comment]
it's fixed now! i'd appreciate a star too man :)!

**Comment by hero4000** [comment]
i check it now Thanks
